// bce/engine/assemble.ts
import type { AgentContext, Behavior } from './types.js';
import { interpolate } from './template.js';

function buildDefaultParams(behavior: Behavior): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [paramName, paramDef] of Object.entries(behavior.params)) {
    if (paramDef.default !== undefined) {
      result[paramName] = paramDef.default;
    } else {
      switch (paramDef.type) {
        case 'string': result[paramName] = ''; break;
        case 'number': result[paramName] = 0; break;
        case 'boolean': result[paramName] = false; break;
        case 'string[]': result[paramName] = []; break;
        case 'number[]': result[paramName] = []; break;
        default: result[paramName] = '';
      }
    }
  }
  return result;
}

interface SectionEntry {
  key: string;
  number: number;
  behaviorName: string;
  prompt: string;
  overriddenBy?: string;
}

export interface AssemblePromptResult {
  prompt: string;
  sectionTrace: SectionEntry[];
}

export function assemblePrompt(
  behaviors: Map<string, Behavior>,
  injectedSections: Map<string, { prompt: string; source: string }>,
  overriddenSections: Map<string, string>,
  agent: AgentContext,
  resolvedParams: Record<string, Record<string, unknown>>,
): AssemblePromptResult {
  const entries: SectionEntry[] = [];

  for (const [behaviorName, behavior] of behaviors) {
    for (const [key, section] of Object.entries(behavior.sections)) {
      const number = parseInt(key.substring(0, 3), 10);
      const context = {
        agent,
        params: resolvedParams[behaviorName] ?? buildDefaultParams(behavior),
      };
      const prompt = interpolate(section.prompt, context, `behavior "${behaviorName}", section "${key}"`);
      const overrideKey = `${behaviorName}:${key}`;
      const overriddenBy = overriddenSections.get(overrideKey);
      entries.push({ key, number, behaviorName, prompt, overriddenBy });
    }
  }

  for (const [key, injected] of injectedSections) {
    const number = parseInt(key.substring(0, 3), 10);
    const context = { agent, params: {} };
    const prompt = interpolate(injected.prompt, context);
    entries.push({ key, number, behaviorName: `_rule:${injected.source}`, prompt });
  }

  entries.sort((a, b) => {
    if (a.number !== b.number) return a.number - b.number;
    return a.behaviorName.localeCompare(b.behaviorName);
  });

  return {
    prompt: entries.map((e) => e.prompt.trim()).join('\n\n'),
    sectionTrace: entries,
  };
}

interface HookEntry {
  behaviorName: string;
  script: string;
  args: string[];
  blocking: boolean;
  order: number;
}

export function assembleHooks(
  behaviors: Map<string, Behavior>,
  agent: AgentContext,
  resolvedParams: Record<string, Record<string, unknown>>,
): Record<string, string> {
  const byLifecycle = new Map<string, HookEntry[]>();

  for (const [behaviorName, behavior] of behaviors) {
    for (const [lifecycle, hook] of Object.entries(behavior.hooks)) {
      if (!byLifecycle.has(lifecycle)) {
        byLifecycle.set(lifecycle, []);
      }
      const context = { agent, params: resolvedParams[behaviorName] ?? buildDefaultParams(behavior) };
      const resolvedArgs = hook.args.map((a) => interpolate(a, context));

      byLifecycle.get(lifecycle)!.push({
        behaviorName,
        script: hook.script,
        args: resolvedArgs,
        blocking: hook.blocking,
        order: hook.order,
      });
    }
  }

  const result: Record<string, string> = {};

  for (const [lifecycle, entries] of byLifecycle) {
    entries.sort((a, b) => {
      if (a.order !== b.order) return a.order - b.order;
      return a.behaviorName.localeCompare(b.behaviorName);
    });

    const lines = [
      '#!/bin/bash',
      '# Generated by BCE — DO NOT EDIT',
      `# Lifecycle: ${lifecycle}`,
      '',
    ];

    for (const entry of entries) {
      lines.push(`# From behavior: ${entry.behaviorName} (order: ${entry.order})`);
      const argsStr = entry.args.length > 0 ? ' ' + entry.args.map((a) => `"${a}"`).join(' ') : '';
      if (entry.blocking) {
        lines.push(`"$BCE_SCRIPTS_DIR/${entry.script}"${argsStr} || exit 1`);
      } else {
        lines.push(`"$BCE_SCRIPTS_DIR/${entry.script}"${argsStr} || true`);
      }
      lines.push('');
    }

    result[lifecycle] = lines.join('\n');
  }

  return result;
}

export function assembleMcpTools(behaviors: Map<string, Behavior>): string[] {
  const toolSet = new Set<string>();
  for (const behavior of behaviors.values()) {
    for (const tool of behavior.mcp_tools) {
      toolSet.add(tool);
    }
  }
  return [...toolSet].sort();
}

export function mergeMcpConfig(
  existingMcpJson: Record<string, unknown>,
  bceMcpTools: string[],
  coordinatorUrl: string,
): Record<string, unknown> {
  const servers = (existingMcpJson.mcpServers ?? {}) as Record<string, unknown>;

  for (const key of Object.keys(servers)) {
    if (key.startsWith('_bce_')) {
      delete servers[key];
    }
  }

  if (bceMcpTools.length > 0) {
    servers['_bce_coordinator'] = {
      type: 'http',
      url: `${coordinatorUrl}/mcp`,
      _bce_tools: bceMcpTools,
    };
  }

  return { ...existingMcpJson, mcpServers: servers };
}

export function assembleEnvVars(
  agent: AgentContext,
  resolvedParams: Record<string, Record<string, unknown>>,
): Record<string, string> {
  return {
    COORDINATOR_AGENT_ID: agent.id,
    COORDINATOR_AGENT_NAME: agent.displayName,
    COORDINATOR_AGENT_PROFILE: agent.profile,
    COORDINATOR_AGENT_MODEL: agent.model,
    BCE_PARAMS: JSON.stringify(resolvedParams),
  };
}
